### ISSUE TITLE
Better error reporting

### ISSUE THREAD

**Issue by tebeka** [353solutions/carrow#19]
Currently when there's an error at the C++ level we return an invalid value, however we don't have the message context.

Since we're a Go library :) I suggest API functions will return struct with value and error message. If the error message is empty - there was no error. Otherwise it'll contain the error message (probably from `status.message()`).

#### carrow.cc
```c++
struct ptr_reply {
    void *ptr;
    const char *error;
};

// ...
if (!status.ok()) {
    return ptr_reply{nullptr, status.message().c_str()};
}
// ...
// No error
return ptr_reply{table, nullptr};
```

#### carrow.go
```go
out = C.some_function()
if out.error != nil {
    msg := C.GoString(out.error)
    C.free(out.error)
    return nil, fmt.Errorf(msg)
}
return NewTableFromPtr(out.ptr), nil
```

**Comment by tebeka** [comment]
@yonidavidson thoughts?

**Comment by yonidavidson** [comment]
A. I agree, we need to make sure we manage our logs only in 1 place (and maybe add debug logs in c++ later on).
B. I wonder if anyone did some work on parsing c++ logs to be more human readble.

**Comment by yonidavidson** [comment]
+ returning a struct gives more flexibility then a pointer (we can add other meta data on the struct later on to help the "go" code).

**Comment by yonidavidson** [comment]
1. One option is to use c++ tuple (like we do in Java/Kotlin) https://en.cppreference.com/w/cpp/utility/tuple
2. I think either part of this issue or a new issue we should expose a go logger into the C++ domain - this way we have one logger system in our codebase. (easier to pass params, compile logs, etc). - this way we can also use traces in simpler way.

**Comment by tebeka** [comment]
> One option is to use c++ tuple (like we do in Java/Kotlin) https://en.cppreference.com/w/cpp/utility/tuple
IMO you won't be able to use C++ tuple (or anything with templates) in `extern C` block

**Comment by tebeka** [comment]
> I think either part of this issue or a new issue we should expose a go logger into the C++ domain - this way we have one logger system in our codebase. (easier to pass params, compile logs, etc). - this way we can also use traces in simpler way.
Yes! Please open an issue for this.
