### ISSUE TITLE
Type specific builders

### ISSUE THREAD

**Issue by tebeka** [353solutions/carrow#3]
Currently we have `FloatArrayBuilder` and `IntArrayBuilder`. They should become `Float64ArrayBuilder ` and `Int64ArrayBuilder` . The `Int64ArrayBuilder` `Append` should get an `int64` as value.

**Comment by yonidavidson** [comment]
What you want is actually a better "description" of the type, right?
Renaming all the way "down the pipe".

**Comment by yonidavidson** [comment]
Why FLOAT64 and not DOUBLE?

**Comment by tebeka** [comment]
> Float64 ( and not Double) to be consistent with GO- right?
Yup
